"""Experiment 5: seed flow on a real xref-stream PDF (generated by pikepdf/QPDF)."""

import pikepdf
import pymupdf as fitz

# Build an xref-stream PDF with QPDF
pdf = pikepdf.new()
pdf.add_blank_page(page_size=(200, 200))
pdf.add_blank_page(page_size=(300, 400))
pdf.save(".scratch/qpdf_xref.pdf", generate_xref_stream=True)

raw = open(".scratch/qpdf_xref.pdf", "rb").read()
print("has classic trailer keyword:", b"trailer" in raw)
print("has XRef stream:", b"/Type /XRef" in raw)

doc = fitz.open(".scratch/qpdf_xref.pdf")
print("pages:", len(doc))
print("ID before:", doc.xref_get_key(-1, "ID"))

seed = "deadbeefdeadbeefdeadbeefdeadbeef"
doc.xref_set_key(-1, "ID", f"[<{seed}><{seed}>]")
print("ID after set:", doc.xref_get_key(-1, "ID"))

doc.save(
    ".scratch/qpdf_xref_enc.pdf",
    encryption=fitz.PDF_ENCRYPT_AES_256,
    user_pw="pw123",
    owner_pw="pw123",
)
doc.close()

raw2 = open(".scratch/qpdf_xref_enc.pdf", "rb").read()
i = raw2.rfind(b"/ID")
print(
    "\nID in encrypted output:",
    raw2[i : i + 90].decode("latin-1") if i >= 0 else "NONE",
)
print("encrypted output has classic trailer:", raw2.rfind(b"trailer") >= 0)

d2 = fitz.open(".scratch/qpdf_xref_enc.pdf")
print("needs_pass:", d2.needs_pass)
print("seed read without password:", d2.xref_get_key(-1, "ID"))
d2.close()
